---
title: "ISSS608 In-Class Exercise #4"
description: |
  In-Class Exercise #4 done by me, myself and I (and guided by Prof Kam).
author:
  - name: Clarence Tay 
    url: https://www.linkedin.com/in/clarencetay/
    affiliation: Singapore Management University - MITB
    affiliation_url: https://scis.smu.edu.sg/master-it-business
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      eval = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.retina = 2)
```

# Getting Started

## Setting up R packages

To start with, [ggstatsplot](https://indrajeetpatil.github.io/ggstatsplot/) and [tidyverse](https://www.tidyverse.org/) packages will be installed (if not yet) and launched using `library()`.

```{r echo = TRUE}
packages = c('ggstatsplot','tidyverse')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
    }
  library(p, character.only = T)
  }
```

## Importing data

```{r}
exam <- read_csv('data/Exam_data.csv')
```

## Working with ggstatsplot

### ANOVA test

#### Parametric
```{r fig.height = 6, fig.width = 8}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "p"
)
```

#### Non-parametric
```{r fig.height = 6, fig.width = 8}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "np"
)
```

#### Bayes
```{r fig.height = 6, fig.width = 8}
set.seed(1234)

ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "bayes"
)
```































